config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root 'toppages#index'

  resources :users, only: [:show, :edit , :index] do 
    get 'follow', :on => :member
  end
  resources :profiles, only: [:create , :update]
  resources :skills , only: [:create]
  resources :works , only: [:create]
  resources :user_links , only: [:create]
  resources :likes , only: [:create] do
    delete '', to: 'likes#destroy', as: :delete , on: :collection
  end


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/like.rb
class Like < ApplicationRecord
  belongs_to :user
  belongs_to :like, class_name: 'User'
end

app/models/profile.rb
class Profile < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImagesUploader
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :user
  belongs_to :skill_master
  enum age: { less1year: 0 , over1year: 1 , over3year:2}

end

app/models/skill_master.rb
class SkillMaster < ApplicationRecord
  # belongs_to :skill
  has_one :skill
end

app/models/user.rb
class User < ApplicationRecord
  extend FriendlyId
  before_create :profile_save 
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :lockable, :omniauthable

  friendly_id :username

  validates_uniqueness_of :username
  validates_presence_of :username
  validates_presence_of :email

  has_one  :profile

  has_many :skills
  accepts_nested_attributes_for :skills, allow_destroy: true, reject_if: :all_blank

  has_many :works
  accepts_nested_attributes_for :works, allow_destroy: true, reject_if: :all_blank

  has_many :user_links
  accepts_nested_attributes_for :user_links, allow_destroy: true, reject_if: :all_blank
  
  has_many :likes
  has_many :follows, through: :likes, source: :like
  has_many :revers_likes , class_name: "Like", foreign_key: "like_id"
  has_many :followers, through: :revers_likes, source: :user

  def profile_save
    self.build_profile
  end

  def follow(user)
    self.likes.find_or_create_by(like_id: user.id)
  end
  
  def unfollow(user)
    follow = self.likes.find_by(like_id: user.id)
    follow.destroy if follow
  end
  
  def follow?(user)
    self.follows.include?(user)
  end
  
end

app/models/user_link.rb
class UserLink < ApplicationRecord
  self.inheritance_column = :_type_disabled
  belongs_to :user
  enum type: { github: 1 , twitter:2, facebook:3, lightbulb:4, blogger:5 }
end

app/models/work.rb
class Work < ApplicationRecord
  belongs_to :user
  mount_uploader :image, ImagesUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

  protected 
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username,:email,:password, :password_confirmation])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email,:password,:remember_me])
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  before_action :authenticate_user!

  def create
    @user = User.find_by(id: params[:user_id])
    respond_to do |format|
      if current_user.follow(@user)
        format.html { redirect_to @user, notice: 'successfully' }
        format.json { render json:{status: "success"}}
      else
        format.html { redirect_to @user, notice: 'error' }
        format.json { render json:{status: "error"}}
      end
    end
  end

  def destroy
    @user = User.find_by(id: params[:user_id])
    respond_to do |format|
      if current_user.unfollow(@user)
        format.html { redirect_to @user, notice: 'successfully' }
        format.json { render json:{status: "success"}}
      else
        format.html { redirect_to @user, notice: 'error' }
        format.json { render json:{status: "error"}}
      end
    end
  end

end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  before_action :authenticate_user!
  before_action :check_permission , only: [:update]

  def update

    respond_to do |format|
      if @profile.update(profile_params)
        format.html { redirect_to edit_user_path(@profile.user_id), notice: 'Proile was successfully updated.' }
        format.json { render :show, status: :ok, location: redirect_back(fallback_location: root_path) }
      else
        format.html { redirect_to edit_user_path(@profile.user_id), notice: 'Proile was successfully updated.' }
        format.json { render :show, status: :ok, location: redirect_back(fallback_location: root_path) }
      end
    end
    

  end

  private 
  def profile_params
    params.require(:profile).permit(
      :user_id,
      :disp_name,
      :birth,
      :biography,
      :image
    )
  end

  def check_permission
    @profile = Profile.find(params[:id])
    return if @profile.user_id == current_user.id
  end

end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :authenticate_user!

  def create    
    skill_params[:skills_attributes].keys.each do |id|
      param = skill_params[:skills_attributes][id]
      if param.has_key?(:_destroy)
        current_user.skills.find_by(id:param[:id]).destroy
      else
        skill = current_user.skills.find_or_initialize_by( id: param[:id]).tap do |s|
          s.skill_master_id = param[:skill_master_id]
          s.age = param[:age]
          s.level = param[:level]
        end
        skill.save
      end
    end
    redirect_back(fallback_location: root_path)
  end

  private 
  def skill_params
    params.require(:user).permit(
      :user_id,
      skills_attributes: [:id, :skill_master_id, :age, :level, :_destroy],
    )
  end
end

app/controllers/toppages_controller.rb
class ToppagesController < ApplicationController
  def index
  end
end

app/controllers/user_links_controller.rb
class UserLinksController < ApplicationController
  before_action :authenticate_user!

  def create
    user_links_param[:user_links_attributes].keys.each do |id|
      param = user_links_param[:user_links_attributes][id]
      if param.has_key?(:_destroy)
        current_user.user_links.find_by(id:param[:id]).destroy
      else
        link = current_user.user_links.find_or_initialize_by( id: param[:id]).tap do |s|
          s.type = param[:type]
          s.link_url = param[:link_url]
        end
        link.save
      end
    end
    redirect_back(fallback_location: root_path)
  end

  def check_permission
    @user_links = UserLink.find(params[:id])
    return if @user_links.user_id == current_user.id
  end

  private 
  def user_links_param
    params.require(:user).permit(
      :user_id,
      user_links_attributes: [:id, :type, :link_url, :_destroy],
    )
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User
      .includes(:profile, :skills, :user_links)
  end

  def show
    @user = User.friendly.find(params[:id])
  end

  def edit
    current_user.skills.build unless current_user.skills.present?
    current_user.user_links.build unless current_user.user_links.present?
    current_user.works.build unless current_user.works.present?
  end

  def follow
    @user = User.friendly.find_by(username: params[:id])
    @follows = @user.follows
      .includes(:profile, :skills, :user_links)

  end

end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  def create
    work_params[:works_attributes].keys.each do |id|
      param = work_params[:works_attributes][id]
      if param.has_key?(:_destroy)
        current_user.works.find_by(id:param[:id]).destroy
      else
        work = current_user.works.find_or_initialize_by( id: param[:id]).tap do |s|
          s.title = param[:title]
          s.description = param[:description]
          s.image = param[:image] if param[:image].present?

          s.url = param[:url]
          s.source_url = param[:source_url]
        end
        work.save
      end
    end
    redirect_back(fallback_location: root_path)
  end

  private 
  def work_params
    params.require(:user).permit(
      :user_id,
      works_attributes: [:id, :title, :description, :url, :source_url, :image,:_destroy],
    )
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/toppages_helper.rb
module ToppagesHelper
end

app/helpers/user_helper.rb
module UserHelper
  def star_rating(num)
    star = ""
    (1..num).each do 
      star += '★'
    end
    star
  end
end

app/views/layouts/_flash_message.html.erb
  <% flash.each do |message_type, message| %>
  <% message_type = "warning" unless ["success","info","warning","denger",].include?(message_type) %>
  <div class="alert alert-<%= message_type %> alert-dismissible" id="layout-alertfadeout">  
      <button type="button" class="close" data-dismiss="alert">×</button>
      <%= message %>
    </div>
  <% end %>

app/views/layouts/_footer.html.erb


<footer class="text-center">
  © Enfollio.
</footer>

app/views/layouts/_navbar.html.erb
<header>
  <nav class="navbar navbar-inverse navbar-static-top">
    <a class="navbar-brand" href="/">Enfollio</a>
    <div class="container">
      <% if current_user %>
        <div class="navbar-header navbar-right">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar-collapse1">
            <span class="sr-only">メニュー</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
        </div>

        <div class="collapse navbar-collapse" id="navbar-collapse1">

          <ul id="navbar-list-menu" class="nav navbar-nav navbar-right visible-sm visible-xs">
              <li><%= link_to "マイページ", user_path(current_user) %></li>
              <li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>
              <li><%= link_to "お気に入りユーザー", follow_user_path(current_user) %>
              <li><%= link_to "ログアウト", destroy_user_session_path,  :method => "delete" %>
          </ul>
          <ul class="nav navbar-nav navbar-right  hidden-sm hidden-xs">

            </li>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
                  <%= image_tag current_user.profile.image , :size => '32x32' , :class=>"img-circle center-block" ,:style=>"float:left" %>
                 <span class="caret"></span>
              </a>
              
              <ul class="dropdown-menu" id="menu-dropdown">
                <li><%= link_to "マイページ", user_path(current_user) %></li>
                <li><%= link_to "プロフィール編集", edit_user_path(current_user) %></li>
                <li><%= link_to "お気に入りユーザー", follow_user_path(current_user) %>
                <li><%= link_to "ログアウト", destroy_user_session_path,  :method => "delete" %>
              </ul>
            </li>
          </ul>
        </div>
      <% else %>

       <div class="collapse navbar-collapse " id="gnavi">
          <ul id="navbar-list-menu" class="nav navbar-nav navbar-right">
            <li><%= link_to "ログイン", new_user_session_path,  class: "btn btn-sm pull-right" %> </li>
          </ul>
        </div>

      <% end %>

    </div>
  </nav>
</header>


app/views/layouts/_star_rating.html.erb
<style>

  .rating{
    display: inline-block;

    position: relative;
    
    width: -webkit-fit-content;
    width: -moz-fit-content;
    width: fit-content;
    height: auto;

    white-space: nowrap;
  }

  .rating:before{
    content: attr(filter);
    position: absolute;
    
    display: block;
    
    color: dodgerblue;
    overflow: hidden;
    pointer-events: none;
    white-space: nowrap;
  }
</style>
<div class="rating" filter="<%= star_rating(star) %>">☆☆☆☆☆</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Enfollio</title>
    <%= csrf_meta_tags %>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link href="https://fonts.googleapis.com/css?family=Signika" rel="stylesheet">


    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="turbolinks-cache-control" content="no-cache">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>
    <div class="container-fluid" style="overflow:hidden">
        
      <%= yield %>
    <%= render 'layouts/footer' %>
  </body>

</html>

app/views/likes/create.html.erb
<h1>Likes#create</h1>
<p>Find me in app/views/likes/create.html.erb</p>

app/views/likes/destroy.html.erb
<h1>Likes#destroy</h1>
<p>Find me in app/views/likes/destroy.html.erb</p>

app/views/profiles/_form.html.erb
<%= form_for(user.profile) do |f| %>
  <%= f.hidden_field :user_id, :value => user.id %>
    <div class="form-group form-inline">
      <%= f.label "表示名", class: "control-label" %>
      <%= f.text_field :disp_name, class: "form-control"%>
      <%= f.label "誕生日", class: "control-label" %>
      <%= f.date_field :birth , class: "form-control"%>
    </div>
    <div class="form-group">

      <%= f.label "自己紹介", class: "control-label" %>
      <%= f.text_area :biography, size: "5x10", class: "form-control" %>
      <%= f.label "画像" , class: "control-label"%>
      <%= f.file_field :image, class: "filestyle" %>

      <%= f.submit "submit", class: "col-xs-offset-5 col-xs-1 btn btn-primary" %>
  </div>
<% end %>

app/views/skills/_form.html.erb


<%= form_for(current_user, url: skills_path, method: :post) do |f| %>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <%= f.hidden_field :user_id, :value => current_user.id %>

    <%= f.nested_fields_for :skills,  wrapper_tag: :tr do |s| %>

      <td class="col-xs-1 text-center"><%= s.remove_nested_fields_link fa_icon "trash", class: 'btn btn-danger btn-circle', role: 'button' %></td>
      <td><%= s.collection_select :skill_master_id, SkillMaster.all, :id, :name ,{} ,{class:"form-control"} %></td>
      <td><%= s.select :age, Skill.ages_i18n.invert, {},class:"form-control" %></td>
      <td><%= s.number_field :level, {class:"form-control"} %></td>

    <% end %>

    <tfoot>
      <tr>
        <td colspan="4" align="left">
          <%= f.add_nested_fields_link :skills , class: 'btn btn-success', role: 'button' do %>
            <%= fa_icon "plus" %> Add
          <% end %>
          <%= f.submit "submit" , class: 'btn btn-primary'%>
        </td>
      </tr>
    </tfoot>
  </table>
</div>
<% end %>


app/views/skills/_lists.html.erb

<div class="row">
  <div class="col-xs-12 col-md-10 col-md-offset-1">
    <% skills.each do | skill | %>
      <div class="col-xs-12 col-md-4">
        <div class="panel panel-default shadow">
          <div class="panel-body">
            <div class="title">
              <h3><%= skill.skill_master.name %></h3>
            </div>
            <div class="description">
              <div class="skill-year">経験年数：<%= skill.age_i18n %></div>
            </div>
            <div class="rating">
              <%= render 'layouts/star_rating' , star: skill.level %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/toppages/index.html.erb
<h1>Toppages#index</h1>
<p>Find me in app/views/toppages/index.html.erb</p>

app/views/user_links/_form.html.erb
<%= form_for(user, url: user_links_path, method: :post) do |f| %>
<div class="table-responsive">
  <table class="table table-striped table-bordered table-hover">
    <%= f.hidden_field :user_id, :value => current_user.id %>

    <%= f.nested_fields_for :user_links,  wrapper_tag: :tr do |s| %>
      <td class="col-xs-1 text-center"><%= s.remove_nested_fields_link fa_icon "trash", class: 'btn btn-danger btn-circle', role: 'button' %></td>

      <td><%= s.select :type, UserLink.types_i18n.invert, {},class:"form-control" %></td>
      <td><%= s.text_field :link_url,class:"form-control" %></td>
    <% end %>
    <tfoot>
      <tr>
        <td colspan="3" align="left">
          <%= f.add_nested_fields_link :user_links, class: 'btn btn-success', role: 'button' do %>
            <%= fa_icon "plus" %> Add
          <% end %>
          <%= f.submit "submit" , class: 'btn btn-primary'%>
        </td>
      </tr>
    </tfoot>
  </table>

</div>
<% end %>

app/views/user_links/_lists.html.erb
<style>

.link-panel{
  border-radius: 8em;	
  padding:4px 0px;
  background-color:#dfdfdf;
}
.link-panel a:link {
  text-decoration:none;
  color: #000;
}
</style>

<div class="col-xs-12 col-md-10 col-md-offset-1">
  <% user_links.each do | link | %>
    <div class="col-xs-6 col-md-3">
      <div class="panel panel-default link-panel">
        <div class="title">
          <%= link_to link.link_url do %>
            <h4><%= fa_icon link.type%> <%= link.type_i18n %></h4>
          <% end %>
        </div>
      </div>
    </div>
  <% end %>
</div>

app/views/userlinks/create.html.erb
<h1>Userlinks#create</h1>
<p>Find me in app/views/userlinks/create.html.erb</p>

app/views/users/edit.html.erb

<style>

table {
  min-width:600px;
}

</style>



<div class="container">
  <div class="row">
    <div class="panel panel-default">
      <div class="panel-heading">プロフィール</div>
      <div class="panel-body">
        <%= render 'profiles/form' , user:current_user %>
      </div>  
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">スキル登録</div>
      <div class="panel-body">
        <%= render 'skills/form' , user:current_user %>  
      </div>  
    </div>

    <div class="panel panel-default">
      <div class="panel-heading">実績登録</div>
      <div class="panel-body">
        <%= render 'works/form' , user:current_user %>  
      </div>  
    </div>



    <div class="panel panel-default">
      <div class="panel-heading">リンク</div>
      <div class="panel-body">
        <%= render 'user_links/form' , user:current_user %>        
      </div>
    </div>
  </div>
</div>

app/views/users/follow.html.erb

<style>
#users-list {
  min-height:400px;
}
#users-list .username {
  color: #14171a;
  font-weight:bold;
  font-size:20px;
}

#users-list .description a:link { color:#14171a; text-decoration:none }
#users-list .description a:visited { color:#14171a; text-decoration:none }
#users-list .description a:hover { color:#14171a; text-decoration:none }
#users-list .description a:active { color:#14171a; text-decoration:none }

#users-list .panel:hover {
  background-color: #f5f8fa;
}
#users-list .panel {
  transition: 0.2s;
}
.skillname {
  display:inline-block;
}
.rating {
  font-size: 20px;
}
.star-area {
  display:inline-block;
  vertical-align: top;
  font-size: 18px;
  padding-right:12px;
}
.star-area .star-num {
  padding-left: 4px;
}
</style>

<section id="users-list">
  <div class="container">
    <% # @follows.each  do |user| %>
      <% (1..10).each do %>
        <% user = current_user %>
      <div class="user-panel-<%= user.id %> col-xs-12 col-md-4">
        <div class="panel panel-default shadow">
          <div class="panel-body">
            <%= image_tag user.profile.image,  :size => '70x70' , :class=>"img-circle", :id=>"profile-image" %>
            <div class="star-area pull-right">
              <% type = current_user.follow?(user) ? "enable" : "disable" %>
              <%= image_tag "common/star_#{type}.png", id:"user-star", type:type ,user_id:user.id ,size:"20x20" %>
              <span class="star-num"><%= user.followers.count %></span>
            </div>
            <div class="description">
              <%= link_to user_path(user) do %>
                <p class="username"><%= user.profile.disp_name %></p>
                <p><%= truncate(user.profile.biography, length:60) %></p>
                <div class="skills">
                  <% user.skills.order("level desc").limit(3).each do |skill| %>
                    <div class="skill">
                      <span class="skillname col-xs-4"><%= skill.skill_master.name %></span>
                      <span class="col-xs-8"><%= render 'layouts/star_rating' , star: skill.level %></span>
                    </div>
                  <% end %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/users/index.html.erb
<% @users.each do |user| %>
  <%= link_to user.username, user_path(user)  %>
<% end %>

app/views/users/show.html.erb
<style>

</style>

<div class="user-header row">
  <div class="logo-area col-xs-12 col-sm-8 col-sm-offset-2">
    <h1 class="logo text-center"><%= @user.profile.disp_name %>'s portfolio</h1>
  </div>
</div>

<div class="row">
  <div class="menu" id="user-menu">
    <nav class="navbar">
      <ul class="nav navbar-nav row">
        <li class="col-xs-6 col-md-2 col-md-offset-2">
          <a href="#profile"><%= fa_icon "user lg"%> PROFILE</a>
        </li>
        <li class="col-xs-6 col-md-2">
          <a href="#skills"><%= fa_icon "exclamation lg"%> SKILLS</a>
        </li>
        <li class="col-xs-6 col-md-2">
          <a href="#works"><%= fa_icon "briefcase lg"%> WORKS&nbsp;</a>
        </li>
        <li class="col-xs-6 col-md-2">
          <a href="#links"><%= fa_icon "link lg"%> LINKS&nbsp;&nbsp;</a>
        </li>
      </ul>
    </nav>
  </div>
</div>

<div class="container">
<section id="profile" class="row">
  <h2 class="text-center header-title"><%= fa_icon "user lg"%>&nbsp;PROFILE</h2>
  <div class="col-xs-12 col-md-4 col-md-offset-1">
    <%= image_tag @user.profile.image,  :size => '300x300' , :class=>"img-circle center-block" %>
  </div>
  <div class="col-xs-12 col-md-6 biography">
    <%= @user.profile.biography %>
  </div>
</section>

<section id="skills" class="row">
  <h2 class="text-center header-title"><%= fa_icon "exclamation lg"%>&nbsp;SKILLS</h2>
  <%= render 'skills/lists' ,skills: @user.skills %>
</section>

<style>
#works .panel {
  min-height:330px;
  max-height:400px;
}
</style>
</div>
<section id="works" class="row">
  <div class="container">
    <h2 class="text-center header-title"><%= fa_icon "briefcase lg"%>&nbsp;WORKS</h2>
  </div>
  <%= render 'works/lists' , works: @user.works %>
</section>

<section id="links" class="row">
  <h2 class="text-center header-title"><%= fa_icon "link lg"%>&nbsp;LINKS</h2>
  <%= render 'user_links/lists' , user_links: @user.user_links %>
</section>

<style>
#fixed-footer-button-area {
  position: fixed;
  bottom: 0;
  width: 100%;
  height: 30px;
  margin:0;
  text-align:right;
  padding: 10px 30px 48px 0;
}
</style>


<div class="row">
  <section id="fixed-footer-button-area">
    <% type = current_user.follow?(@user) ? "enable" : "disable" %>
    <%= image_tag "common/star_#{type}.png", id:"user-star", type:type ,user_id:@user.id ,size:"40x40" %>
  </section>
</div>

app/views/works/_form.html.erb
<%= form_for(user, url: works_path, method: :post) do |f| %>
<div class="table-responsive">

  <table class="table table-striped table-bordered table-hover">
    <%= f.hidden_field :user_id, :value => user.id %>
    <tr>
      <thead>
        <th></th>
        <th>サービス名</th>
        <th>説明</th>
        <th>サービスURL</th>
        <th>ソースコードURL</th>
        <th>画像</th>

      </thead>
    </tr>
    <tr>
      <%= f.nested_fields_for :works,  wrapper_tag: :tr do |s| %>
        <td class="col-xs-1 text-center"><%= s.remove_nested_fields_link fa_icon "trash", class: 'btn btn-danger btn-circle', role: 'button' %></td>

        <td><%= s.text_field :title ,class:"form-control" %></td>
        <td><%= s.text_field :description ,class:"form-control" %></td>
        <td><%= s.text_field :url,class:"form-control" %></td>
        <td><%= s.text_field :source_url,class:"form-control" %></td>
        <td>
          <%= s.label :image, class: "btn btn-default" %>
          <%= s.file_field :image, class: "filestyle" ,style: "display:none;" %>
        </td>


      <% end %>
    </tr>

    <tfoot>
      <tr>
        <td colspan="6" align="left">
          <%= f.add_nested_fields_link :works, class: 'btn btn-success', role: 'button' do %>
            <%= fa_icon "plus" %> Add
          <% end %>
          <%= f.submit "submit" , class: 'btn btn-primary'%>
        </td>
      </tr>
    </tfoot>
  </table>

</div>
<% end %>

app/views/works/_lists.html.erb
<div class="row">
  <div class="col-xs-12 col-md-12">
    <div class="row">
      <% works.each do | work | %>
        <div class="col-xs-12 col-md-4">
          <div class="panel panel-default shadow">
            <div class="image">
              <%= image_tag work.image, :class=>"img-responsive" %>
            </div>
            <div class="panel-body">
              <div class="title">
                <h3><%= work.title %>
              </div>
              <div class="description">
                <%= work.description %>
              </div>
              <% unless work.source_url.empty? %>
                <div class="url">
                  <%= link_to "ソースコード" , work.source_url %>
                </div>
              <% end %> 
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/works/create.html.erb
<h1>Works#create</h1>
<p>Find me in app/views/works/create.html.erb</p>